server:
  port: 8081
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/ck_meet?createDatabaseIfNotExist=TRUE&useUnicode=YES&characterEncoding=UTF-8&serverTimezone=CET
    username: root
    password: Nkpdpgnv1.
    initialization-mode: always
    driverClassName: com.mysql.cj.jdbc.Driver
