server:
  port: 8081
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/ck_meet?createDatabaseIfNotExist=TRUE&useUnicode=YES&characterEncoding=UTF-8&serverTimezone=CET
    username: admin
    password: admin
    initialization-mode: always
